import { workspaceState } from '../state/workspace.svelte';
import { uiState } from '../state/ui.svelte';
import { showToast } from '../components/Toast.svelte';
import { benchmark } from './benchmark.svelte';
import { tick } from 'svelte';

/**
 * Global service for managing WebSocket connections and simulation state.
 * Uses Svelte 5 runes (`$state`) for deep reactivity across the application.
 */
export class SimulationService {
	/** The active WebSocket connection to the Python backend. */
	socket: WebSocket | null = null;

	/** Reactive flag indicating whether the WebSocket is currently open. */
	isConnected = $state(false);

	/** Reactive array storing all possible next-state branches generated by the engine. */
	possibilities = $state<any[]>([]);

	/** Reactive dictionary storing acceptance/rejection results for String Judge mode. */
	judgeResults = $state<Record<string, string>>({});

	/** Reactive array tracking history snapshots for the history table. */
	history = $state<any[]>([]);

	// Simulation Control State
	tick = $state(0);
	speed = $state(1.5);
	mode = $state<'pseudorandom' | 'guided' | 'random'>('pseudorandom');
	isHalted = $state(false);
	isPlaying = $state(false);

	systemState = $state({
		name: 'Binary Adder',
		div: [] as number[],
		dsv: [] as number[]
	});

	// History stack for stepping back (internal)
	private simHistoryStack = $state<any[]>([]);
	private autoPlayInterval: ReturnType<typeof setInterval> | null = null;

	// Initial state snapshots for restart
	private initialNodes: any = null;
	private initialEdges: any = null;
	private initialSystemState: any = null;

	/**
	 * Initializes the WebSocket connection to the backend engine.
	 */
	connect() {
		if (this.socket) return;
		this.socket = new WebSocket('ws://localhost:8000/ws/simulate');

		this.socket.onopen = () => {
			this.isConnected = true;
			console.log('Connected to WebSnapse Simulation Engine');
		};

		this.socket.onmessage = async (event) => {
			const data = JSON.parse(event.data);
			
			// If we are tracking compute time, end it now
			benchmark.endCompute();

			if (data.type === 'judge_result') {
				this.judgeResults[data.string] = data.status;
			} else {
				this.possibilities = data.possibilities;

				// In pseudorandom mode, automatically pick the first possibility
				if (this.mode === 'pseudorandom' && this.possibilities.length > 0) {
					const firstBranch = this.possibilities[0];
					await this.applyBranch(firstBranch);
					
					// If the engine reports the system has halted, stop playback
					if (firstBranch.is_halted) {
						this.isHalted = true;
						this.pause();
						showToast('Simulation halted', 'info');
					}
				} else if (this.mode === 'random' && this.possibilities.length > 0) {
					// Pick a random branch
					const randomIndex = Math.floor(Math.random() * this.possibilities.length);
					const randomBranch = this.possibilities[randomIndex];
					await this.applyBranch(randomBranch);

					if (randomBranch.is_halted) {
						this.isHalted = true;
						this.pause();
						showToast('Simulation halted', 'info');
					}
				} else if (this.possibilities.length === 0 && this.tick > 0) {
					this.isHalted = true;
					this.pause();
					showToast('Simulation halted', 'info');
				}
			}
		};

		this.socket.onclose = () => {
			this.isConnected = false;
			this.socket = null;
		};
	}

	snapshotInitialState() {
		this.initialNodes = JSON.parse(JSON.stringify(workspaceState.nodes));
		this.initialEdges = JSON.parse(JSON.stringify(workspaceState.edges));
		this.initialSystemState = JSON.parse(JSON.stringify(this.systemState));
		this.recordHistory();
	}

	sendState(payload: any) {
		if (this.socket && this.isConnected) {
			if (payload.type === 'step') benchmark.startCompute();
			this.socket.send(JSON.stringify(payload));
		}
	}

	handleStep() {
		if (!this.isConnected || this.isHalted) return;

		this.sendState({
			type: 'step',
			tick: this.tick,
			nodes: workspaceState.nodes.map((n: any) => ({
				id: n.id,
				neuronType: n.data.neuronType,
				spikes: n.data.spikes,
				rules: n.data.rules || []
			})),
			edges: workspaceState.edges.map((e: any) => ({
				source: e.source,
				target: e.target,
				weight: e.data?.weight ?? 1
			})),
			div: this.systemState.div,
			dsv: this.systemState.dsv
		});
	}

	async applyBranch(pos: any) {
		benchmark.startRender();
		const firedNeurons = new Set<string>();
		const firedRules: string[] = [];
		const ruleNames = this.getOrderedRules();
		const dv = pos.dv || [];
		const iv = pos.iv || [];

		dv.forEach((selected: number, idx: number) => {
			if (selected === 1 && ruleNames[idx]) firedRules.push(ruleNames[idx]);
		});

		iv.forEach((fired: number, idx: number) => {
			if (fired === 1 && ruleNames[idx]) {
				if (!firedRules.includes(ruleNames[idx])) firedRules.push(ruleNames[idx]);
			}
		});

		// Save to step-back history
		this.simHistoryStack.push({
			nodes: JSON.parse(JSON.stringify(workspaceState.nodes)),
			edges: JSON.parse(JSON.stringify(workspaceState.edges)),
			systemState: JSON.parse(JSON.stringify(this.systemState)),
			tick: this.tick
		});

		const nodeDelayMap = this.buildNodeDelayMap(pos.dsv || [], pos.div || []);
		const closedNodeIds = new Set<string>();
		nodeDelayMap.forEach((delay, id) => { if (delay > 0) closedNodeIds.add(id); });

		workspaceState.nodes = workspaceState.nodes.map((n: any, i: number) => {
			const ntype = n.data.neuronType;
			let newSpikes = n.data.spikes;

			if (ntype === 'input' || ntype === 'Input') {
				const train = String(n.data.spikes);
				if (train.length > 0 && train[0] === '1') firedNeurons.add(n.id);
				newSpikes = train.substring(1);
			} else if (ntype === 'output' || ntype === 'Output') {
				const currentTrain = typeof n.data.spikes === 'string' ? n.data.spikes : '';
				const prevAccumulated = currentTrain.split('').filter((c: string) => c === '1').length;
				const newAccumulated = pos.c_k[i] ?? prevAccumulated;
				const delta = newAccumulated - prevAccumulated;
				newSpikes = currentTrain + (delta > 0 ? '1' : '0');
			} else {
				if (pos.c_k[i] !== undefined) newSpikes = pos.c_k[i];
				if (pos.rule_contribution && pos.rule_contribution[i] < 0) firedNeurons.add(n.id);
			}

			return {
				...n,
				data: {
					...n.data,
					spikes: newSpikes,
					delay: nodeDelayMap.get(n.id) ?? 0,
					isFiring: !closedNodeIds.has(n.id) && firedNeurons.has(n.id)
				}
			};
		});

		workspaceState.edges = workspaceState.edges.map((e: any) => ({
			...e,
			data: {
				...e.data,
				isFiring: firedNeurons.has(e.source) && !closedNodeIds.has(e.source) && !closedNodeIds.has(e.target)
			}
		}));

		this.systemState.div = pos.div;
		this.systemState.dsv = pos.dsv;

		// Record in table history
		if (this.history.length > 0) {
			const lastEntry = this.history[this.history.length - 1];
			const ruleByNode: Record<string, string> = {};
			firedRules.forEach((fr) => {
				const parts = fr.split(': ');
				if (parts.length >= 2) ruleByNode[parts[0]] = parts.slice(1).join(': ');
			});
			lastEntry.ruleByNode = ruleByNode;
		}

		this.tick++;
		this.recordHistory();
		this.possibilities = [];

		// Ensure guided mode also respects halting if the user picks a halting branch
		if (pos.is_halted) {
			this.isHalted = true;
			this.pause();
		}

		// Wait for Svelte 5 to flush DOM changes for re-render timing
		await tick();
		benchmark.endRender();
	}

	togglePlayPause() {
		if (this.isPlaying) {
			this.pause();
		} else {
			if (!this.isConnected) {
				showToast('Not connected to engine', 'error');
				return;
			}
			if (this.isHalted) {
				showToast('Simulation is halted', 'warning');
				return;
			}
			this.play();
		}
	}

	play() {
		if (this.autoPlayInterval) return;
		this.isPlaying = true;
		const intervalMs = Math.max(100, 1000 / this.speed);
		this.autoPlayInterval = setInterval(() => this.handleStep(), intervalMs);
	}

	pause() {
		this.isPlaying = false;
		if (this.autoPlayInterval) {
			clearInterval(this.autoPlayInterval);
			this.autoPlayInterval = null;
		}
	}

	setSpeed(newSpeed: number) {
		this.speed = newSpeed;
		if (this.isPlaying) {
			this.pause();
			this.play();
		}
	}

	restart() {
		this.pause();
		if (this.simHistoryStack.length > 0) {
			const firstState = this.simHistoryStack[0];
			workspaceState.nodes = firstState.nodes;
			workspaceState.edges = firstState.edges;
			this.systemState = firstState.systemState;
			this.tick = firstState.tick;
		} else if (this.initialNodes) {
			workspaceState.nodes = JSON.parse(JSON.stringify(this.initialNodes));
			workspaceState.edges = JSON.parse(JSON.stringify(this.initialEdges));
			this.systemState = JSON.parse(JSON.stringify(this.initialSystemState));
			this.tick = 0;
		}
		this.isHalted = false;
		this.simHistoryStack = [];
		this.possibilities = [];
		this.resetSocket();
		this.recordHistory();
	}

	stepBack() {
		if (this.simHistoryStack.length > 0) {
			const prevState = this.simHistoryStack.pop();
			workspaceState.nodes = prevState.nodes;
			workspaceState.edges = prevState.edges;
			this.systemState = prevState.systemState;
			this.tick = prevState.tick;
			this.isHalted = false;
			this.possibilities = [];
			
			if (this.history.length > 0) {
				this.history.pop();
				if (this.history.length > 0) {
					this.history[this.history.length - 1].ruleByNode = {};
				}
			}
		}
	}

	private resetSocket() {
		if (this.socket && this.isConnected) {
			this.socket.send(JSON.stringify({ type: 'reset' }));
			this.history = [];
		}
	}

	private recordHistory(firedRules: string[] = []) {
		const nodeStates: Record<string, any> = {};
		workspaceState.nodes.forEach((n: any) => {
			nodeStates[n.data.id] = { spikes: n.data.spikes, type: n.data.neuronType };
		});

		this.history.push({
			tick: this.tick,
			nodeStates,
			ruleByNode: {}
		});
	}

	private getOrderedRules() {
		let orderedRules: string[] = [];
		workspaceState.nodes.forEach((n: any) => {
			const ntype = n.data.neuronType;
			if (ntype === 'input' || ntype === 'Input' || ntype === 'output' || ntype === 'Output') return;
			const rules = n.data.rules || [];
			rules.forEach((r: any) => orderedRules.push(`${n.data.id}: ${r}`));
		});
		return orderedRules;
	}

	private buildNodeDelayMap(dsv: number[], div: number[]) {
		const delayMap = new Map<string, number>();
		let ruleIdx = 0;
		workspaceState.nodes.forEach((n: any) => {
			const ntype = n.data.neuronType;
			if (ntype === 'input' || ntype === 'Input' || ntype === 'output' || ntype === 'Output') return;
			const ruleCount = (n.data.rules || []).length;
			let maxDelay = 0;
			for (let r = 0; r < ruleCount; r++) {
				const globalR = ruleIdx + r;
				if (div[globalR] === 1) maxDelay = Math.max(maxDelay, dsv[globalR]);
			}
			delayMap.set(n.id, maxDelay);
			ruleIdx += ruleCount;
		});
		return delayMap;
	}
}

export const simulation = new SimulationService();