/**
 * Global service for managing WebSocket connections and simulation state.
 * Uses Svelte 5 runes (`$state`) for deep reactivity across the application.
 */
export class SimulationService {
    /** The active WebSocket connection to the Python backend. */
    socket: WebSocket | null = null;
    
    /** Reactive flag indicating whether the WebSocket is currently open. */
    isConnected = $state(false);
    
    /** Reactive array storing all possible next-state branches generated by the engine. */
    possibilities = $state([]);
    
    /** Reactive dictionary storing acceptance/rejection results for String Judge mode. */
    judgeResults = $state<Record<string, string>>({});
    
    /** Reactive array tracking the history of confirmed simulation states for stepping backward. */
    history = $state<any[]>([]);

    /**
     * Initializes the WebSocket connection to the backend engine.
     * Sets up event listeners for open, message, and close events.
     */
    connect() {
        this.socket = new WebSocket('ws://localhost:8000/ws/simulate');

        this.socket.onopen = () => {
            this.isConnected = true;
            console.log('Connected to WebSnapse Simulation Engine');
        };

        this.socket.onmessage = (event) => {
            const data = JSON.parse(event.data);
            if (data.type === 'judge_result') {
                this.judgeResults[data.string] = data.status;
            } else {
                // Update reactive state with new possibilities
                this.possibilities = data.possibilities;
            }
        };

        this.socket.onclose = () => {
            this.isConnected = false;
        };
    }

    /**
     * Sends the current visual graph state to the backend engine to calculate the next tick.
     * 
     * @param payload - The system state payload containing nodes, edges, tick count, and delay vectors.
     */
    sendState(payload: any) {
        if (this.socket && this.isConnected) {
            this.socket.send(JSON.stringify(payload));
        }
    }

    /**
     * Resets the backend simulation engine and clears the local history array.
     */
    reset() {
        if (this.socket && this.isConnected) {
            this.socket.send(JSON.stringify({ type: 'reset' }));
            this.history = [];
        }
    }
}

export const simulation = new SimulationService();